/**
 * Created on 2025/1/23
 */
package svga.audio

//TODO
public class AVPlayerClass {
    var id: String = "";
    private var seekPlay: Bool = false

    public init() {
    }

    // 单曲播放
    public func play() {
    }

    // 设置进度
    public func seek(seek: Int32, autoplay!: Bool = true) {
    }

    // 暂停
    public func pause() {
    }

    // 停止
    public func stop() {
    }

    // 删除
    public func release() {
    }
}
