/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
package svga.workers

import ohos.image.*
import stdx.encoding.base64.*


public class MessageEvents {
    var src: String
    var key: String
    var types: String
    var dir: String

    public init(src: String, key: String, types: String, dir: String) {
        this.src = src
        this.key = src
        this.types = src
        this.dir = src
    }
}