/**
 * Created on 2025/1/9
 */
package ohos_app_cangjie_svga.model

//public interface TextMap {
//  var text: string
//  var size?: Length
//  var color?: string
//  var offset?: TextOffset
//  var family?: string
//  var style?: string
//  var weight?: SVGAFontWeight
//}
//
//public interface class TextOffset {
//    var x: Float64
//  var y: Float64
//}
//
//public type SVGAFontWeight =
//  'normal' | 'bold' | 'bolder' | 'lighter'
//    | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900