[dependencies]

[package]
  cjc-version = "0.58.3"
  compile-option = "-O2"
  description = "nothing here"
  link-option = ""
  name = "zlib4cj"
  output-type = "dynamic"
  src-dir = "src"
  target-dir = ""
  version = "1.0.2"
  package-configuration = {}
  scripts = {}

