/**
 * Created on 2025/3/12
 */
package svga.player

internal import tpc.UIKit.*
internal import tpc.UIKit.component_interop.*
internal import tpc.UIKit.matrix4.*
internal import tpc.BasicServicesKit.*
internal import tpc.AbilityKit.*
internal import tpc.UIKit.animator.*
//internal import ohos.component.*
//internal import ohos.ability.*
//internal import ohos.image.*
//internal import ohos.resource_manager.*
//internal import ohos.animator.*
//internal import ohos.file_fs.*
//internal import ohos.matrix4.*
////internal import ohos.prompt_action.*
//internal import ohos.ability.*
//internal import ohos.hilog.*
//internal import kit.UIKit.PromptAction
//internal import kit.UIKit.PromptAction