/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
package svga.player

internal import ohos.base.*
internal import ohos.component.*
internal import ohos.ability.*
internal import ohos.image.*
internal import ohos.resource_manager.*
internal import ohos.animator.*
internal import ohos.file_fs.*
internal import ohos.matrix4.*
internal import ohos.ability.*
internal import ohos.hilog.*
internal import svga.global.*
internal import kit.UIKit.PromptAction