/**
 * Created on 2025/1/14
 */
package svga.player
public class Player {
//    private var _onFinished: ?() -> Unit = None
//    private var _onFrame: ?(Float64) -> Unit = None
//    private var _onPercentage: ?(Float64) -> Unit = None
//      // 倍率
//    private var _speed: Float64 = 1.0
//    private var _playerController: StateController
//
//    init(UIContext: UIContext, context: Context, canvasRenderer: CanvasRenderingContext2D) {
//        this._uiContext = UIContext
//        this._context = context
//
//        this._context2D = canvasRenderer
//        this._init()
//        this._playerController = new StateController(this)
//        this._sourceManager = new SourceManager(context)
//  }
//
//     private _sourceManager: SourceManager
//
//  public get sourceManager(): SourceManager {
//    return this._sourceManager
//  }
//
//  private _pageIndex: string = ''
//
//  public get pageIndex(): string {
//    return this._pageIndex
//  }
//
//  public set pageIndex(value: string) {
//    this._pageIndex = value
//  }
}
