/**
 * Created on 2025/1/11
 */
package ohos_app_cangjie_svga.utils

import ohos.file_fs.*

public class FileManager {
  static func saveAudio (src: String, fileDir: String): Int64 {
//    try {
//      if (!FileFs.access(fileDir)) {
//        FileFs.mkdir(fileDir)
//      }
//      var filePath = fileDir + '/' + util.generateRandomUUID() + '.mp3'
//      var file = fs.openSync(filePath, fs.OpenMode.READ_WRITE | fs.OpenMode.CREATE)
//      var baseHelper = util.Base64Helper()
//      var buf = baseHelper.decodeSync(src)
//      fs.writeSync(file.fd, buf.buffer)
//      return file.fd
//    } catch (err: Exception) {
//      AlertDialog.show({
//        message: '保存沙箱失败' + JSON.stringify(err)
//      })
//      return -1
//    }
        0
  }
}